apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.address }}:{{ .Values.image.tag }}"    
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: Europe/Stockholm    
          - name: LANG
            value: sv_SE.utf8
          - name: JAVA_OPTIONS
            value: -Didp.home=/opt/shibboleth-idp -Didp.keystore.pw={{ .Values.idp.keystore.pw }} -Didp.truststore.pw={{ .Values.idp.truststore.pw }} -Didp.logfiles=/opt/shibboleth-logs         
        name: {{ .Release.Name }}
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP          
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File  
        volumeMounts:
        - mountPath: opt/shibboleth-idp
          name: {{ .Release.Name }}-pvc
        - mountPath: opt/shibboleth-logs
          name: {{ .Release.Name }}-logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Release.Name }}-pvc
        persistentVolumeClaim:
          claimName:  {{ .Release.Name }}
      -name: {{ .Release.Name }}-logs
         emptyDir: {} # Default uses node disk    
status: {}