# Setup common for running an IdP or a Hub (for SP4)

# Enable our "comprehensive" module
--module=shibboleth

# Route access logging through standard SLF4J logging API
#etc/jetty-requestlog.xml

# Do not expose contexts to web.
jetty.server.default.showContexts=false

##################################
## Network/Host/Port configuration
##################################

## TLS host and port to bind to
jetty.ssl.host=0.0.0.0
#jetty.ssl.port=8443

# Non-TLS host and port to bind to
jetty.http.host=0.0.0.0
#jetty.http.port=8080

######################################
## Keystore properties for TLS support
######################################

# Keystore file path (relative to $jetty.base)
jetty.sslContext.keyStorePath=${idp.home}/credentials/idp-backchannel.p12
jetty.sslContext.trustStorePath=${idp.home}/credentials/idp-backchannel.p12
# Keystore type
jetty.sslContext.keyStoreType=PKCS12
jetty.sslContext.trustStoreType=PKCS12

# Keystore passwords
jetty.sslContext.keyStorePassword=${idp.keystore.pw}
jetty.sslContext.trustStorePassword=${idp.truststore.pw}
jetty.sslContext.keyManagerPassword=${idp.keystore.pw}

# Deny SSL renegotiation
jetty.sslContext.renegotiationAllowed=false

# Skip SNI hostcheck
jetty.ssl.sniHostCheck=false

# Suppress node name in JSESSIONID values
# This assumes a non-clustered Jetty deploy
#jetty.sessionIdManager.workerName=